output_dir: ~/experiments/

dataset:
  class: FB15k237Inductive
  path: ~/datasets/knowledge_graphs/
  version: {{ version }}

task:
  class: InductiveKnowledgeGraphCompletion
  model:
    class: NBFNet
    input_dim: 32
    hidden_dims: [32, 32, 32, 32, 32, 32]
    message_func: distmult
    aggregate_func: pna
    short_cut: yes
    layer_norm: yes
    dependent: yes
    remove_one_hop: yes
  criterion: bce
  num_negative: 32
  strict_negative: yes
  adversarial_temperature: 0.5
  sample_weight: no
  full_batch_eval: yes

optimizer:
  class: Adam
  lr: 5.0e-3

engine:
  gpus: {{ gpus }}
  batch_size: 64

train:
  num_epoch: 0

metric: mrr

checkpoint: ~/experiments/InductiveKnowledgeGraphCompletion/FB15k237Inductive/NBFNet/2024-01-25-00-49-33/model_epoch_2.pth
